apiVersion: v1
kind: Service
metadata:
  name: animal-service
spec:
  # type: LoadBalancer
  selector:
    app: animal-service
  ports:
  # - port: 53101
  - port: 80
    targetPort: 53100

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: animal-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: animal-service
  template:
    metadata:
      labels:
        app: animal-service
    spec:
      containers:
      - name: animal-service
        image: sanjaygeorge16/animal-service
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 53100

