export default [
    "Cyclops",
    "Ogre",
    "Leprechauns",
    "Gnomes",
    "Goblins",
    "Faeries",
    "Gorgon",
    "Mermaid",
    "Aqrabuamelu",
    "Minotaur",
    "Centaurs",
    "Fauns",
    "Werewolf",
    "Loch Ness Monster",
    "Griffin",
    "Phoenix",
    "Basilisk",
    "Unicorn",
    "Dragon",
    "Bigfoot",
    "Hydra",
    "Pontianak",
    "Banshee",
    "Dybbuk",
    "Vampire"
]