apiVersion: v1
kind: Service
metadata:
  name: adjective-service
spec:
  # type: LoadBalancer
  selector:
    app: adjective-service
  ports:
  # - port: 53100
  - port: 80
    targetPort: 53100

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adjective-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: adjective-service
  template:
    metadata:
      labels:
        app: adjective-service
    spec:
      containers:
      - name: adjective-service
        image: sanjaygeorge16/adjective-service
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "200Mi"
            cpu: "100m"
        ports:
        - containerPort: 53100

