apiVersion: v1
kind: Service
metadata:
  name: creature-service
spec:
  # type: LoadBalancer
  selector:
    app: creature-service
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: creature-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: creature-service
  template:
    metadata:
      labels:
        app: creature-service
    spec:
      containers:
      - name: creature-service
        image: sanjaygeorge16/creature-service
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80

