apiVersion: v1
kind: Service
metadata:
  name: color-service
spec:
  # type: LoadBalancer
  selector:
    app: color-service
  ports:
  # - port: 53102
  - port: 80
    targetPort: 53100

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: color-service
  template:
    metadata:
      labels:
        app: color-service
    spec:
      containers:
      - name: color-service
        image: sanjaygeorge16/color-service
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 53100

