apiVersion: v1
kind: Service
metadata:
  name: nick-name-generator
spec:
  type: LoadBalancer
  selector:
    app: nick-name-generator
  ports:
  - port: 80
    targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nick-name-generator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nick-name-generator
  template:
    metadata:
      labels:
        app: nick-name-generator
    spec:
      containers:
      - name: nick-name-generator
        image: sanjaygeorge16/nick-name-generator
        ports:
        - containerPort: 3000

